{{- if not .Values.pgconnectionUseExistingSecret }}
{{- range .Values.pgConnections }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "dirt-tile-server.labels" $ | nindent 4 }}
type: Opaque
data:
    pgconnection: {{ .secretValue | b64enc | quote }}
{{- end }}
{{- end}}
