apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgconnectonSecretName }}
  labels:
    {{- include "dirt-tile-server.labels" . | nindent 4 }}
type: Opaque
data:
    pgconnection: {{ .Values.pgconnection | b64enc | quote }}
